interface StringByString {
  [key: string]: any
}

export function trans(locale: any, section: string, element: string) {
  if (Object.keys(translations).indexOf(locale) === -1) {
    locale = 'en'
  }
  return translations[locale][section][element]
}

export const translations: StringByString = {
  en: {
    menu: {
      home: 'Home',
      start: 'Start',
      rules: 'Rules',
      'world-map': 'World Map',
      winner: 'Winner',
      'space-balls': 'SpaceBalls',
      partner: 'Partner',
      transporter: 'Transporter',
      faq: 'Faq',
    },
    home: {
      // game-section
      'for-players': 'For players',
      'winner-prize': 'Winner prize',
      'winner-prize-text': 'Find all 7 GalaxyBalls in your country and win 10.000 €/$',
      'form-team': 'Form team',
      'form-team-text':
        'The GalaxyBalls are scattered all over the country. Form a team and go on an adventurous quest with friends to increase your chances of finding multiple GalaxyBalls and win the top prize of 10,000 € /$',
      price: 'Price for each ball',
      'price-text': 'For every GalaxyBalls you find you will receive 1.000 € /$',

      // rule-section
      rules: 'Rules',
      'rules-text': `At the beginning of the game, 7 GalaxyBalls will be distributed in a country and the approximate location will be published here on the website under "WORLD MAP" as well as in the GalaxyBalls app under "WORLD MAP". 
      With the GalaxyBalls app under "RADAR", the balls can be located and found in the immediate vicinity. Once a GalaxyBalls has been found, the QR code on the ball must be scanned to be registered as an official finder. After all GalaxyBalls have been found, you must return them undamaged to one of our locations to receive your prize money.`,
      'rules-text-1': 'If you find a GalaxyBalls, you will receive 1,000 € /$ /Crypto',
      'rules-text-2': 'If you find all 7 GalaxyBalls you will get even € /$ /Crypto',

      // world-map-section
      'world-map-title': 'World Map',
      'world-map-text': `Here you can see in which country the GalaxyBalls are currently located. But you can also find out in which future country the GalaxyBalls will land.`,

      // winners-section
      'winners-title': 'Winners',
      'winners-text':
        'Here you can find all the winners who found a GalaxyBalls in your country. Find the balls and get entered in the rangliste. The more GalaxyBalls you find, the more entries you get!',
      'winners-text-1': 'Guaranteed payouts of winnings',
      'winners-text-2': 'You can find all the rules in our terms and conditions',
      'winners-button': 'Full list',

      // conditions-section
      'conditions-title': 'The condition for the start',
      'conditions-text': `Download the GalaxyBalls app and register with your email address. Then all you have to do is find 5 SpaceBalls (virtual balls) to fully activate your GalaxyRadar and you're ready to go.`,

      // prize-section
      'prize-title': 'Your prizes are waiting for you',
      'prize-text': `Many galactic orbs are already approaching Earth. Be among the first to go in search of them and get a Galactic Reward!`,

      // faq-section
      'faq-title': 'FAQ',
      'faq-description': 'Here you will find all important and frequently asked questions.',
      'question-description-1': 'Who can participate?',
      'answer-description-1': 'Anyone can participate, no matter where they are from. The only requirement is to install the GalaxyBalls app.',
      'question-description-2': 'Where can I find the balls?',
      'answer-description-2':
        'At the beginning of the game, seven balls are distributed to the selected country. The approximate locations can be found under World Map on the website and in the GalaxyBalls app. Turn on the radar and find them.',
      'question-description-3': 'What do I do when I find a bullet?',
      'answer-description-3':
        'When you find a ball, you need to scan the QR code on it. In the menu you will find the scanner icon, click on it. Once you do this, you will be registered in our server as an official finder and the orb will be deactivated.',
      'question-description-4': 'How much can I win?',
      'answer-description-4':
        'If you find one ball alone or in a team, you win 1000 €/$ or crypto in national currency. If you find all 7 balls, the jackpot is 10,000 €/$ or crypto.',
      'question-description-5': 'Who hides the balls?',
      'answer-description-5':
        'This task has been entrusted to our official transporter. He takes the GalaxyBalls to 7 different locations. Their location is randomly generated by a system.',
      'question-description-6': 'How do I get my prize money?',
      'answer-description-6':
        'The GalaxyBalls finders have to bring the found balls undamaged to a certain place in the respective country to get their prize money.',
    },
    transporter: {
      'page-title': 'Transporter',
      desc: `A difficult task can only be undertaken by someone with sufficient experience.`,
      'insta-link': `Galaxy-Transporter`,
      title: `Our official Transporter of GalaxyBalls`,
      details: `He is a master of transportation. 
      <br />
      <br />
      His job is to move the GalaxyBalls from one country to another which he has done dozens of times.He knows exactly what he is doing. He makes sure that the games will run safely and that the rules are followed.
      <br />
      <br />
      For this reason we have hired a transporter as our agent for the distribution of the balls. He alone will make sure that the GalaxyBalls come to you. If you find one of them, you will also meet the transporter.`,
    },
    partners: {
      title: 'partners',
      desc: `Here you can find all the partners who worked on the GalaxyBalls project and supported us with their know-how. Each of them has contributed
      something that made this project unique, and that's how we got to this result.`,
      'card-1-title': 'Blend',
      'card-1-desc': 'Consulting',
      'card-1-detail': `Blend has helped us in the areas of consulting and ideas. He was one of the first partners in this project and has led to further contacts as with aldin then also with the Transporter.`,
      'card-2-title': 'Aldin',
      'card-2-desc': 'Multitasking',
      'card-2-detail': `Aldin has supported us in the area of consulting, ideas and photography. We also owe him the cooperation with our current transporter. Aldin is very multitasking and a very reliable partner.`,
      'card-3-title': 'Besnik',
      'card-3-desc': 'Transporter',
      'card-3-detail': `Besnik tafallari is not only our official GalaxyBalls transporter but also the best jason statham double in the world. We found him so interesting that a collaboration was inevitable.`,
      'card-4-title': 'Samafro',
      'card-4-desc': 'Videomaker',
      'card-4-detail': `Samafaro has made us some very nice video footage from around the world. His recordings are of the highest quality, as is his work.`,
      'card-5-title': 'John',
      'card-5-desc': 'Designer',
      'card-5-detail': `John is a master of design, we owe him the website, the app and much more. His work is great and it was a pleasure to work with him and have many sleepless nights.`,
      'card-6-title': 'Alicia',
      'card-6-desc': 'Soft Consulting',
      'card-6-detail': `Alicia is a developer in Germany. She was responsible for consulting the project and was a great support for us.`,
      'card-7-title': 'Crowdfunding',
      'card-7-desc': 'List of all Superheroes',
      'card-7-detail': `Here you will soon find all the superheroes who supported us on ulule.com and Kickstarter. Join us!`,
      'card-8-title': 'Do you want to join us?',
      'card-8-desc': 'Contact us!',
      'card-8-detail': `We are always ready to collaborate with other talents. Whether you're a designer, artist, influencer, etc., just drop us a line so we can get you involved in the Galaxyballs project!`,
      officialsite: 'Official site',
    },
    'space-balls': {
      // intro section
      title: 'SpaceBalls',
      desc: 'The SpaceBalls are here and waiting for you. Experience unique moments in Augment Realty that you have never seen before!',

      // chance section
      'chance-to-win': 'Your chance to win!',
      steps: 'Steps',
      'find-balls': 'Find Balls',
      scan: 'Scan',
      win: 'Win',

      // feature-section
      'about-space-balls': 'Something about SpaceBalls',
      'about-text': 'Three things you should know about the SpaceBalls',
      'about-desc-1': 'Your level increases and you are entered in a rank',
      'about-desc-2': 'They are scattered all over the world',
      'about-desc-3': 'They come in different colors, sizes and some are rare',
      'find-a-ball': 'What happens when you find a SpaceBall?',
      'find-a-ball-text': 'Three other important things you should know',
      'find-desc-4': 'You get experience points every time',
      'find-desc-5': 'All SpaceBalls land in your bag and many have different functions that help you advance in the game',
      'find-desc-6': 'You will get 3 different things that will bring you further',

      // adventure-section
      'what-else': 'What else',
      'adventure-coming-soon': 'The greatest adventure is coming soon...',
      'adventure-text': `Two games are available in the app and provide more fun and adventure. <br />
      <br />
      The second part of the game is especially interesting for gamers and explorers. Every day new adventures, challenges and very valuable
      SpaceBalls are waiting for you.
      <br />
      <br />
      With some of these SpaceBalls you can unlock more game options to increase your level, get ranked and win prizes. Besides, there is also a
      store to help you achieve your goals faster.`,

      // values-section
      rankinglist: 'Rankinglist',
      'rankinglist-desc': 'Be entered in the rankinglist so that everyone can see you.',
      chat: 'Chat',
      'chat-desc': 'Chat with your team and with other users worldwide',
      team: 'Team',
      'team-desc':
        'Form a team to search for the SpaceBalls and GalaxyBalls. This will increase your chance to find all the balls even faster and more efficiently.',
      winners: 'Winners',
      'winners-desc': 'Win great prizes. The more balls you find, the bigger your gifts will be.',

      // final-section
      finally: 'Finally',
      'search-and-enjoy': 'Search and enjoy!',
      'search-and-enjoy-desc':
        'Discover many treasures hidden in each SpaceBall. Great surprises are waiting for you that you have never seen before. Go alone or with your friends on the hunt for many galactic balls and fill your treasure chest. Check the app daily to never miss an opportunity.',
      'you-can-also': 'You can also...',
      'extend-bag': 'Extend your bag to collect more SpaceBalls',
      'get-your-detector': 'Get your detector and find the rest of the SpaceBalls',
      'participate-events': 'Participate in special events to find rare SpaceBalls',

      // more-section
      'more-about': 'More about our SpaceBalls',
      'more-about-text': 'Look at all the different SpaceBalls note which are the most valuable ones',
    },
    footer: {
      'footer-text': 'available soon',
    },
  },

  fr: {
    menu: {
      home: 'Accueil',
      start: 'Départ',
      rules: 'Règles',
      'world-map': 'World Map',
      winner: 'Gagnant',
      'space-balls': 'SpaceBalls',
      partner: 'Partenaire',
      transporter: 'Transporteur',
      faq: 'Faq',
    },
    home: {
      // game-section
      'for-players': 'Pour les joueurs',
      'winner-prize': 'Prix du vainqueur',
      'winner-prize-text': 'Trouvez les 7 boules de Cristal dans votre pays et gagnez 10.000 € /$/crypto',
      'form-team': 'Former une équipe',
      'form-team-text': `Les boules de cristal sont éparpillées dans tout le pays. Formez une équipe et partez à l'aventure avec vos amis pour augmenter vos chances de trouver plusieurs boules de cristal et de gagner le premier prix de 10 000 € /$/crypto`,
      price: 'Prix pour chaque balle',
      'price-text': 'Pour chaque GalaxyBalls que vous trouverez, vous gagnez 1 000 € /$/ crypto',

      // rule-section
      rules: 'Règles',
      'rules-text': `Au début du jeu, 7 boules de cristal seront cachées dans un pays et leur emplacement approximatif sera publié ici sur le site web sous "WORLD MAP" ainsi que dans l'application GalaxyBalls sous "WORLD MAP". Avec l'application GalaxyBalls sous "RADAR", les GalaxyBalls peuvent être localisées et trouvées à proximité immédiate. Une fois qu'une GalaxyBalls a été trouvée, le code QR doit être scanné pour être enregistré en tant que gagnant officiel. Une fois toutes trouvés, vous devez les rapporter intacts à l'un de nos sites pour recevoir votre prix.`,
      'rules-text-1': 'Si vous trouvez une GalaxyBalls, vous recevrez 1 000 euros / USD / Crypto.',
      'rules-text-2': 'Si vous trouvez les 7 Galaxyballs, vous obtiendrez même 10.000 Euro / USD/ Crypto.',

      // world-map-section
      'world-map-title': 'World Map',
      'world-map-text': `Vous pouvez voir ici dans quel pays les GalaxyBalls se trouvent actuellement. Vous pouvez également découvrir dans quel futur pays les GalaxyBalls vont atterrir.`,

      // winners-section
      'winners-title': 'Gagnants',
      'winners-text': `Ici vous pouvez trouver tous les gagnants qui ont trouvé un GalaxyBalls dans votre pays. Trouve les GalaxyBalls et sois classé dans le Rangliste mondial, plus tu en trouves, plus tu obtiens d'entrées !`,
      'winners-text-1': 'Paiements garantis des gains',
      'winners-text-2': 'Vous pouvez trouver toutes les règles dans nos conditions générales.',
      'winners-button': 'Liste complète',

      // conditions-section
      'conditions-title': `Condition pour le départ`,
      'conditions-text': `Téléchargez l'application GalaxyBalls et enregistrez-vous avec votre adresse e-mail. Il ne vous reste plus qu'à trouver 5 SpaceBalls (boules virtuelles) pour activer complètement votre GalaxyRadar et vous êtes prêt à partir.`,

      // prize-section
      'prize-title': 'Vos prix vous attendent',
      'prize-text': `De nombreux boules galactiques s'approchent déjà de la Terre. Soyez parmi les premiers à partir à leur recherche et obtenez une récompense galactique!`,

      // faq-section
      'faq-title': 'FAQ',
      'faq-description': 'Vous trouverez ici toutes les questions importantes et fréquemment posées.',
      'question-description-1': 'Qui peut participer?',
      'answer-description-1': `Tout le monde peut participer, peu importe d'où il vient. La seule condition est d'installer l'application GalaxyBalls`,
      'question-description-2': 'Où puis-je trouver les balles?',
      'answer-description-2': `Au début du jeu, les 7 boules seront caché dans le pays choisi. Les emplacements approximatifs peuvent être déterminés sous World Map sur le site et dans l'application GalaxyBalls. Activez le radar et trouvez-les.`,
      'question-description-3': 'Que dois-je faire quand je trouve une balle?',
      'answer-description-3': `Si tu trouves une GalaxyBalls, tu dois scanner le code QR qui s'y trouve. Dans le menu, tu trouveras l'icône du scanner, clique dessus. Une fois fait, tu seras enregistré sur notre serveur en tant que trouveur officiel et la boule sera désactivée.`,
      'question-description-4': 'Combien puis-je gagner?',
      'answer-description-4':
        'Si tu trouves une GalaxyBalls, seul ou en équipe, tu gagnes 1000 €/$ ou crypto. Si tu trouves les 7 alors le jackpot est de 10.000 €/$ ou crypto.',
      'question-description-5': 'Qui cache les GalaxyBalls?',
      'answer-description-5':
        'Cette tâche a été confiée à notre transporteur officiel. Il emmène les GalaxyBalls dans 7 endroits différents. Leur emplacement est généré aléatoirement par un système.',
      'question-description-6': 'Comment puis-je obtenir mon prix?',
      'answer-description-6': 'Les vainqueurs doivent apporter les GalaxyBalls intactes à un endroit précis du pays pour recevoir leur prix.',
    },
    transporter: {
      'page-title': 'TRANSPORTEUR',
      desc: `Une tâche difficile ne peut être entreprise que par une personne ayant suffisamment d'expérience.`,
      'insta-link': `Galaxy-Transporter`,
      title: `Notre transporteur officiel de GalaxyBalls`,
      details: `C'est un maître du transport.
      <br />
      <br />
      Son travail consiste à déplacer les GalaxyBalls d'un pays à l'autre, ce qu'il a fait des dizaines de fois. Il s'assure que les jeux se déroulent en toute sécurité et que les règles sont respectées.
      <br />
      <br />
      C'est pourquoi nous avons engagé un transporteur comme agent pour la distribution des GalaxyBalls. Lui seul s'assurera que les boules de cristal arrivent jusqu'à vous. Si vous trouvez l'une d'entre elles, vous rencontrerez également le transporteur.`,
    },
    partners: {
      title: 'Partenaires',
      desc: `Vous trouverez ici quelques-uns des partenaires qui ont travaillé sur le projet GalaxyBalls et nous ont apporté leur soutien. Chacun d'entre eux a apporté une contribution qui a rendu ce projet unique et c'est ainsi que nous sommes arrivés à ce résultat.`,
      'card-1-title': 'Blend',
      'card-1-desc': 'Consulting',
      'card-1-detail': `Blend nous a aidé dans les domaines du conseil et des idées. Il a été l'un des premiers partenaires de ce projet et a conduit à d'autres contacts comme avec aldin puis aussi avec Le Transporteur.`,
      'card-2-title': 'Aldin',
      'card-2-desc': 'Multitâche',
      'card-2-detail': `Aldin nous a soutenu dans le domaine du conseil, des idées et de la photographie. Nous lui devons également la collaboration avec notre transporteur actuel. Aldin est très polyvalent et un partenaire très fiable.`,
      'card-3-title': 'Besnik',
      'card-3-desc': 'Transporteur',
      'card-3-detail': `Besnik tafallari n'est pas seulement notre transporteur officiel de GalaxyBalls mais aussi le meilleur sosie de Jason Statham au monde. Nous l'avons trouvé si intéressant qu'une collaboration était inévitable.`,
      'card-4-title': 'Samafro',
      'card-4-desc': 'Videomaker',
      'card-4-detail': `Samafaro nous a fait de très belles séquences vidéo du monde entier. Ses enregistrements sont de la plus haute qualité, tout comme son travail.`,
      'card-5-title': 'John',
      'card-5-desc': 'Designer',
      'card-5-detail': `John est un maître du design, nous lui devons le site web, l'application et bien plus encore. Son travail est formidable et ce fut un plaisir de travailler avec lui et d'avoir passé de nombreuses nuits blanches.`,
      'card-6-title': 'Alicia',
      'card-6-desc': 'Conseil en logiciels',
      'card-6-detail': `Alicia est une développeuse en Allemagne. Elle était responsable de la consultation du projet et nous a apporté un grand soutien.`,
      'card-7-title': 'Crowdfunding',
      'card-7-desc': 'Liste de tous les superhéros',
      'card-7-detail': `Vous trouverez bientôt ici tous les super-héros qui nous ont soutenus sur ulule.com et Kickstarter. Rejoignez-nous!`,
      'card-8-title': 'Voulez-vous vous joindre à nous?',
      'card-8-desc': 'Contactez nous!',
      'card-8-detail': `Nous sommes toujours prêts à collaborer avec d'autres talents. Que vous soyez un designer, un artiste, un influenceur, etc., écrivez-nous pour que nous puissions vous impliquer dans le projet Galaxyballs!`,
      officialsite: 'Site officiel',
    },
    'space-balls': {
      // intro section
      title: 'SpaceBalls',
      desc: `Les SpaceBalls sont là et vous attendent. Vivez des moments uniques dans réalité augmentée que vous n'avez jamais vus auparavant !`,

      // chance section
      'chance-to-win': 'Votre chance de gagner!',
      steps: 'Étapes',
      'find-balls': 'Trouver',
      scan: 'Scanner',
      win: 'Gagner',

      // feature-section
      'about-space-balls': 'Quelque chose à propos des SpaceBalls',
      'about-text': 'Trois choses à savoir sur les SpaceBalls',
      'about-desc-1': 'Ton niveau augmente et tu es inscrit dans un classement',
      'about-desc-2': 'Ils sont dispersés dans le monde entier',
      'about-desc-3': 'Il y en a de différentes couleurs, tailles et certains sont rares',
      'find-a-ball': 'Que se passe-t-il lorsque tu trouves une SpaceBall?',
      'find-a-ball-text': 'Trois autres choses importantes que tu dois savoir',
      'find-desc-4': `Tu gagnes des points d'expérience à chaque fois.`,
      'find-desc-5': `Toutes les SpaceBalls atterrissent dans ton sac et beaucoup ont différentes fonctions qui t'aident à progresser dans le jeu.`,
      'find-desc-6': 'Tu obtiendras 3 choses différentes qui te permettront de progresser',

      // adventure-section
      'what-else': `Quoi d'autre`,
      'adventure-coming-soon': 'La plus grande aventure arrive bientôt...',
      'adventure-text': `Deux jeux sont disponibles dans l'application pour encore plus de plaisir et d'aventure. <br />
      <br />
      Le second est particulièrement intéressant pour les gamers et les explorateurs. Chaque jour, de nouvelles aventures, de nouveaux défis et de très précieuses SpaceBalls t'attendent.
      <br />
      <br />
      Avec certaines de ces SpaceBalls, tu peux débloquer d'autres options de jeu pour augmenter ton niveau, obtenir des entrées dans le classement et gagner des prix. Il y a également une boutique qui t'aidera à atteindre tes objectifs plus rapidement.`,

      // values-section
      rankinglist: 'Rankinglist',
      'rankinglist-desc': 'Soyez inscrit dans le rankingliste pour que tout le monde puisse vous voir.',
      chat: 'Chat',
      'chat-desc': `Chattez avec votre équipe et avec d'autres utilisateurs dans le monde entier`,
      team: 'Équipe',
      'team-desc':
        'Formez une équipe pour chercher les SpaceBalls et GalaxyBalls. Cela augmentera vos chances de trouver toutes les boules encore plus rapidement et plus efficacement.',
      winners: 'Gagnants',
      'winners-desc': 'Gagnez de superbes prix. Plus vous trouvez de boules, plus vos cadeaux seront importants.',

      // final-section
      finally: 'Enfin',
      'search-and-enjoy': 'cherchez et amusez-vous!',
      'search-and-enjoy-desc': `Découvrez de nombreux trésors cachés dans chaque SpaceBall. De grandes surprises vous attendent que vous n'avez jamais vues auparavant. Pars seul ou avec tes amis à la chasse aux nombreuses boules galactiques et remplis ton coffre à trésor. Consultez l'application tous les jours pour ne jamais manqué une occasion.`,
      'you-can-also': 'Tu peut également...',
      'extend-bag': 'Elargir ton sac pour collecter plus de SpaceBalls',
      'get-your-detector': 'Acheter un détecteur pour trouver les SpaceBalls correspondantes',
      'participate-events': 'Participer à des événements spéciaux pour trouver des SpaceBalls en édition limitée',

      // more-section
      'more-about': 'En savoir plus sur nos SpaceBalls',
      'more-about-text': 'Regarde les différentes SpaceBalls et retiens celles qui ont le plus de valeur.',
    },
    footer: {
      'footer-text': 'disponible soon',
    },
  },

  es: {
    menu: {
      home: 'Home',
      start: 'Inicio',
      rules: 'Reglas',
      'world-map': 'World Map',
      winner: 'Ganadores',
      'space-balls': 'SpaceBalls',
      partner: 'Colaboradores',
      transporter: 'Transportistas',
      faq: 'Faq',
    },
    home: {
      // game-section
      'for-players': 'Para los jugadores',
      'winner-prize': 'Premio para el ganador',
      'winner-prize-text': 'Encuentra las 7 GalaxyBalls en tu país y gana 10.000 € /$',
      'form-team': 'Formar un equipo',
      'form-team-text':
        'Las GalaxyBalls están repartidas por todo el país. Forma un equipo y aventúrate en una búsqueda con tus amigos para aumentar vuestras posibilidades de encontrar varias GalaxyBalls y ganar el primer premio de 10.000 euros / dólares.',
      price: 'Premio por cada bola',
      'price-text': 'Por cada GalaxyBall encontrada recibirás 1.000 € /$',

      // rule-section
      rules: 'Reglas',
      'rules-text': `Al principio del juego, se distribuyen 7 GalaxyBalls en un país y la ubicación aproximada se publica aquí en la página web en "MAPA DEL MUNDO", así como en la App GalaxyBalls en "MAPA DEL MUNDO". Con la App GalaxyBalls en "RADAR", se pueden localizar las bolas y encontrarlas en las inmediaciones. Una vez que se ha encontrado una GalaxyBall, hay que escanear el código QR de la bola para registrarse como buscador oficial. Una vez encontradas todas las GalaxyBalls, deberás devolverlas sin daños a uno de nuestros puntos para recibir el dinero del premio.`,
      'rules-text-1': 'Si encuentras una GalaxyBalls, recibirás 1.000 €/$/ criptomonedas',
      'rules-text-2': 'Si encuentras las 7 GalaxyBalls, recibirás nada menos que 10.000 €/$/ criptomonedas',

      // world-map-section
      'world-map-title': 'Mapa del mundo',
      'world-map-text': `Aquí puedes ver en qué país se encuentran actualmente las GalaxyBalls. También puedes averiguar en qué país futuro se encontrarán las GalaxyBalls.`,

      // winners-section
      'winners-title': 'Ganador',
      'winners-text':
        'Aquí puedes encontrar todos los ganadores que han encontrado una GalaxyBall en tu país.Encuentra las bolas y entra en la clasificación. Cuantas más GalaxyBalls encuentres, más puestos obtendrás.',
      'winners-text-1': 'Pago garantizado de las ganancias',
      'winners-text-2': 'Encontrará todas las normas en nuestras Condiciones Generales',
      'winners-button': 'Lista completa',

      // conditions-section
      'conditions-title': `El requisito para empezar`,
      'conditions-text': `Descarga la App GalaxyBalls y regístrate con tu dirección de correo electrónico. Entonces, todo lo que tienes que hacer es encontrar 5 SpaceBalls (bolas virtuales) para activar completamente tu GalaxyRadar y ya estarás listo para empezar.`,

      // prize-section
      'prize-title': 'Tus premios te esperan',
      'prize-text': `Muchas bolas galácticas ya se están acercando a la Tierra. Sé de los primeros en ir en su búsqueda y recibe una recompensa galáctica.`,

      // faq-section
      'faq-title': 'PREGUNTAS FRECUENTES',
      'faq-description': 'Aquí encontrará todas las preguntas importantes y frecuentes.',
      'question-description-1': '¿Quién puede participar?',
      'answer-description-1': `Cualquiera puede participar, no importa de dónde sea. El único requisito es instalar la App GalaxyBalls.`,
      'question-description-2': '¿Dónde puedo encontrar las bolas?',
      'answer-description-2': `Al principio del juego, se distribuyen siete bolas en el país seleccionado. Las ubicaciones aproximadas se pueden encontrar en el Mapa del Mundo en la página web y en la App GalaxyBalls. Enciende el radar y encuéntralos.`,
      'question-description-3': '¿Qué hago si encuentro una bola?',
      'answer-description-3': `Si encuentras una bola, tienes que escanear el código QR que hay en ella. En el menú encontrarás el icono de escaneado, haz clic en él. Una vez hecho esto, quedarás registrado en nuestro servidor como buscador oficial y la bola se desactivará.`,
      'question-description-4': '¿Cuánto puedo ganar?',
      'answer-description-4':
        'Si encuentras una bola solo o en equipo, ganas 1000 euros / dólares o criptomonedas en moneda nacional. Si encuentra las 7 bolas, el bote es de 10.000 euros / dólares o criptomonedas.',
      'question-description-5': '¿Quién esconde las bolas?',
      'answer-description-5':
        'Esta tarea se dejó en manos del transportista oficial de Galaxy. Él lleva las bolas a 7 lugares diferentes que lanza un generador aleatorio.',
      'question-description-6': '¿Cómo recibo el dinero del premio?',
      'answer-description-6':
        'Los que encuentren las GalaxyBalls tienen que llevar las bolas sin daños a un lugar determinado del país respectivo para recibir el dinero del premio.',
    },
    transporter: {
      'page-title': 'TRANSPORTISTAS',
      desc: `Una tarea difícil sólo puede ser emprendida por alguien que tenga suficiente experiencia.`,
      'insta-link': `Transportista de la Galaxy`,
      title: `Nuestro transportista oficial de las GalaxyBalls`,
      details: `Es un maestro del transporte. 
      <br />
      <br />
      Su trabajo consiste en transportar las GalaxyBalls de un país a otro, algo que ha hecho decenas de veces, y sabe perfectamente lo que hace. Se encarga de que los juegos se desarrollen con seguridad y de que se cumplan las normas.
      <br />
      <br />
      Por ello, hemos contratado a un transportista como agente para la distribución de las GalaxyBalls. Sólo él se encargará de que las GalaxyBalls te lleguen a ti. Si encuentras una de ellas, también te encontrarás con el transportista.`,
    },
    partners: {
      title: 'Colaboradores',
      desc: `Aquí puede encontrar algunos de los socios que han trabajado en el proyecto GalaxyBalls y nos han apoyado con sus conocimientos. Cada uno de ellos ha aportado algo que ha hecho único este proyecto y así es como hemos llegado a este resultado.`,
      'card-1-title': 'Blend',
      'card-1-desc': 'Asesor',
      'card-1-detail': `Blend nos ayudó en las áreas de asesoramiento e ideas. Fue uno de los primeros colaboradores de este proyecto y nos dio a conocer otros contactos como Aldin y luego también el transportista.`,
      'card-2-title': 'Aldin',
      'card-2-desc': 'Multitasking',
      'card-2-detail': `Aldin nos ha apoyado en materia de asesoramiento, ideas y fotografía. También le debemos la colaboración con nuestro actual transportista. Aldin es muy polivalente y un colaborador muy fiable.`,
      'card-3-title': 'Besnik',
      'card-3-desc': 'Transportista',
      'card-3-detail': `Besnik Tafallari no sólo es nuestro transportista oficial de GalaxyBalls, sino también el mejor doble de Jason Statham del mundo. Nos pareció tan interesante que la colaboración fue inevitable.`,
      'card-4-title': 'Samafro',
      'card-4-desc': 'Creador de vídeos',
      'card-4-detail': `Samafaro nos ha hecho vídeos muy bonitos de todo el mundo. Sus grabaciones son de la más alta calidad, al igual que su trabajo.`,
      'card-5-title': 'John',
      'card-5-desc': 'Diseñador',
      'card-5-detail': `John es un maestro del diseño, le debemos la web, la app y mucho más. Su trabajo es estupendo y fue un placer trabajar con él y pasar muchas noches sin dormir.`,
      'card-6-title': 'Alicia',
      'card-6-desc': 'Asesora de software',
      'card-6-detail': `Alicia es desarrolladora en Alemania. Se encargó de asesorar el proyecto y fue un gran apoyo para nosotros.`,
      'card-7-title': 'Crowdfunding',
      'card-7-desc': 'Lista de todos los superhéroes',
      'card-7-detail': `Aquí encontrarás pronto a todos los superhéroes que nos han apoyado en ulule.com y en Kickstarter. ¡Participa!`,
      'card-8-title': '¿Le gustaría unirse a nosotros?',
      'card-8-desc': 'Póngase en contacto con nosotros.',
      'card-8-detail': `Siempre estamos dispuestos a colaborar con otros talentos. Si eres diseñador, artista, influencer, etc., ponte en contacto con nosotros para que te involucremos en el proyecto Galaxyballs.`,
      officialsite: 'Página web oficial',
    },
    'space-balls': {
      // intro section
      title: 'SpaceBalls',
      desc: 'Las SpaceBalls están aquí y te esperan. ¡Vive momentos únicos en Realidad aumentada que nunca antes habías visto!',

      // chance section
      'chance-to-win': '¡Su oportunidad de ganar!',
      steps: 'Pasos',
      'find-balls': 'Encuentre',
      scan: 'Escanee',
      win: 'Gane',

      // feature-section
      'about-space-balls': 'Más información sobre SpaceBalls',
      'about-text': 'Tres cosas que debe saber  sobre SpaceBalls',
      'about-desc-1': 'Tu nivel aumenta y entras en una lista de clasificación',
      'about-desc-2': 'Están dispersas por todo el mundo',
      'about-desc-3': 'Vienen en diferentes colores, tamaños y algunas son raras',
      'find-a-ball': '¿Qué pasa cuando encuentras una SpaceBall?',
      'find-a-ball-text': 'Otras tres cosas importantes que debes saber',
      'find-desc-4': 'Obtienes puntos de experiencia',
      'find-desc-5': 'Todas las SpaceBalls acaban en tu bolsillo y muchas tienen diferentes funciones que te ayudan a progresar en el juego.',
      'find-desc-6': 'Obtienes 3 cosas diferentes que te ayudarán a avanzar',

      // adventure-section
      'what-else': 'Qué más',
      'adventure-coming-soon': 'La mayor aventura está por llegar...',
      'adventure-text': `Hay dos juegos disponibles en la App que proporcionan aún más diversión y aventura. <br />
      <br />
      La segunda parte del juego es especialmente interesante para los jugadores y exploradores. Cada día te esperan nuevas aventuras, retos y valiosísimas SpaceBalls.
      <br />
      <br />
      Con algunas de estas SpaceBalls puedes desbloquear más opciones de juego para aumentar tu nivel, conseguir puestos en el ranking y ganar premios. También hay una tienda que te ayudará a alcanzar tus objetivos más rápidamente.`,

      // values-section
      rankinglist: 'Lista de clasificación ',
      'rankinglist-desc': 'Ingresa en la lista de clasificación para que todos puedan verte.	',
      chat: 'Chat',
      'chat-desc': 'Chatea con tu equipo y con otros usuarios de todo el mundo',
      team: 'Equipo',
      'team-desc':
        'Forma un equipo para buscar las SpaceBalls y GalaxyBalls. Esto aumenta las posibilidades de encontrar todas las bolas de forma más rápida y eficiente.',
      winners: 'Ganadores',
      'winners-desc': 'Gana grandes premios. Cuantas más bolas encuentres, más grandes serán tus regalos.',

      // final-section
      finally: 'En conclusión',
      'search-and-enjoy': '¡busque y disfrute!',
      'search-and-enjoy-desc':
        'Descubre muchos tesoros escondidos en cada SpaceBall. Te esperan grandes sorpresas que nunca has visto antes. Ve a la caza de muchas bolas galácticas solo o con tus amigos y llena tu cofre del tesoro. Consulta la App a diario para asegurarte de no perder ninguna oportunidad.',
      'you-can-also': 'También puedes...',
      'extend-bag': 'Ampliar tu bolsa para recoger más SpaceBalls',
      'get-your-detector': 'Comprar un detector para encontrar las SpaceBalls correctas.',
      'participate-events': 'Participar en eventos especiales para encontrar ediciones limitadas de SpaceBalls.',

      // more-section
      'more-about': 'Más información sobre nuestras SpaceBalls',
      'more-about-text': 'Observa las diferentes SpaceBalls y acuérdate de cuáles son las más valiosas',
    },
    footer: {
      'footer-text': 'disponible pronto',
    },
  },

  de: {
    menu: {
      home: 'Home',
      start: 'Start',
      rules: 'Regeln',
      'world-map': 'World Map',
      winner: 'Gewinner',
      'space-balls': 'SpaceBalls',
      partner: 'Partner',
      transporter: 'Transporter',
      faq: 'Faq',
    },
    home: {
      // game-section
      'for-players': 'Für Spieler',
      'winner-prize': 'Preis des Gewinners',
      'winner-prize-text': 'Finde alle 7 GalaxyBalls in deinem Land und gewinne 10.000 € /$',
      'form-team': 'Team bilden',
      'form-team-text':
        'Die GalaxyBalls sind über das ganze Land verstreut. Bilde ein Team und gehe mit Freunden auf eine abenteuerliche Suche, um eure Chancen zu erhöhen, mehrere GalaxyBalls zu finden und den Hauptpreis von 10.000 € /$ zu gewinnen.',
      price: 'Preis für jede Kugel',
      'price-text': 'Für jeden gefundenen GalaxyBalls erhälst du 1.000 € /$',

      // rule-section
      rules: 'Regeln',
      'rules-text': `Zu Beginn des Spiels werden 7 GalaxyBalls in einem Land verteilt und der ungefähre Standort wird hier auf der Website unter “WORLD MAP” sowie in der GalaxyBalls-App unter “WORLD MAP” veröffentlicht. Mit der GalaxyBalls-App unter "RADAR" können die Kugeln geortet und in der näheren Umgebung gefunden werden. Hat man einen GalaxyBalls gefunden, muss der QR-Code auf der Kugel gescannt werden, um als offizieller Finder registriert zu werden. Nachdem alle GalaxyBalls gefunden wurden, musst du sie unbeschädigt an einem unserer Standorte abgeben, um dein Preisgeld zu erhalten.`,
      'rules-text-1': 'Wenn du einen GalaxyBalls findest, erhältst du 1.000 €/$/ crypto',
      'rules-text-2': 'Wenn du alle 7 GalaxyBalls findest, erhältst du sogar 10.000 €/$/ crypto',

      // world-map-section
      'world-map-title': 'World Map',
      'world-map-text': `Hier siehst du in welchem Land sich die GalaxyBalls derzeit befinden. Du kannst aber auch erfahren in welches zukünftige Land die GalaxyBalls landen werden.`,

      // winners-section
      'winners-title': 'Gewinner',
      'winners-text':
        'Hier findest du alle Gewinner, die eine GalaxyBalls in deinem Land gefunden haben. Finde die Kugeln und werde in die Rangliste eingetragen. Je mehr GalaxyBalls du findest, desto mehr Einträge erhältst du!',
      'winners-text-1': 'Garantierte Auszahlungen von Gewinnen',
      'winners-text-2': 'Alle Regeln finden Sie in unseren Allgemeinen Geschäftsbedingungen',
      'winners-button': 'Vollständige Liste',

      // conditions-section
      'conditions-title': `Die Bedingung für den Start`,
      'conditions-text': `Lade die GalaxyBalls-App herunter und registriere dich mit deiner E-Mail-Adresse. Dann musst du nur noch 5 SpaceBalls (virtuelle Bälle) finden, um dein GalaxyRadar vollständig zu aktivieren, und schon kannst du loslegen.`,

      // prize-section
      'prize-title': 'Deine Preise warten auf dich',
      'prize-text': `Viele galaktische Kugeln nähern sich bereits der Erde. Sei unter den Ersten, die sich auf die Suche nach ihnen macht und erhalte eine Galaktische Belohnung!`,

      // faq-section
      'faq-title': 'FAQ',
      'faq-description': 'Hier finden Sie alle wichtigen und häufig gestellten Fragen.',
      'question-description-1': 'Wer kann teilnehmen?',
      'answer-description-1': `Jeder kann mitmachen, egal woher er kommt. Die einzige Voraussetzung ist die GalaxyBalls-App zu installieren.`,
      'question-description-2': 'Wo kann ich die Kugeln finden?',
      'answer-description-2': `Zu Beginn des Spiels werden 7 Kugeln in das ausgewählte Land verteilt. Die ungefähren Standorte können unter World Map auf der Website und in der GalaxyBalls-App ermittelt werden. Schalte den Radar ein und finde sie.`,
      'question-description-3': 'Was tue ich, wenn ich eine Kugel finde?',
      'answer-description-3': `Wenn du eine Kugel findest, musst du den QR-Code darauf scannen. Im Menü findest du das Scanner-Symbol, klicke es an. Danach wirst du auf unserem Server als offizieller Finder registriert und die Kugel wird deaktiviert.`,
      'question-description-4': 'Wie viel kann ich gewinnen?',
      'answer-description-4':
        'Wenn du alleine oder im Team eine Kugel findest, gewinnst du 1000 €/$ oder Krypto in nationaler Währung. Wenn du alle 7 Kugeln findest, beträgt der Jackpot 10.000 €/$ oder Krypto.',
      'question-description-5': 'Wer versteckt die kugeln?',
      'answer-description-5':
        'Diese Aufgabe wurde dem offiziellen Galaxy Transporter überlassen. Er bringt die Kugeln an 7 verschiedene Orte, die ein Zufallsgenerator ausspuckt.',
      'question-description-6': 'Wie bekomme ich mein Preisgeld?',
      'answer-description-6':
        'Die Finder der GalaxyBalls müssen die gefundenen Kugeln unbeschädigt an einen bestimmten Ort im jeweiligen Land bringen, um ihr Preisgeld zu erhalten.',
    },
    transporter: {
      'page-title': 'TRANSPORTER',
      desc: `Eine schwierige Aufgabe kann nur von jemandem übernommen werden, der über ausreichende Erfahrung verfügt.`,
      'insta-link': `Galaxy-Transporter`,
      title: `Unser offizieller Transporter der GalaxyBalls`,
      details: `Er ist ein Meister des Transports. 
      <br />
      <br />
      Seine Aufgabe ist es, die GalaxyBalls von einem Land in ein anderes zu transportieren, was er schon dutzende Male getan hat, und er weiß genau, was er tut. Er sorgt dafür, dass die Spiele sicher laufen und dass die Regeln eingehalten werden.
      <br />
      <br />
      Aus diesem Grund haben wir einen Transporter als unseren Agenten für die Verteilung der GalaxyBalls eingestellt. Er allein wird dafür sorgen, dass die GalaxyBalls zu dir kommen. Wenn du einen von ihnen findest, wirst du auch den Transporter treffen.`,
    },
    partners: {
      title: 'Partners',
      desc: `Hier finden Sie einige Partner, die am GalaxyBalls-Projekt mitgearbeitet und uns mit ihrem Know-how unterstützt haben. Jeder von ihnen hat etwas beigetragen, dass dieses Projekt einzigartig gemacht hat und so sind wir zu diesem Ergebnis gekommen.`,
      'card-1-title': 'Blend',
      'card-1-desc': 'Berater',
      'card-1-detail': `Blend hat uns in den Bereichen Beratung und Ideen geholfen. Er war einer der ersten Partner in diesem Projekt und hat zu weiteren Kontakten wie mit aldin und dann auch mit dem Transporter geführt.`,
      'card-2-title': 'Aldin',
      'card-2-desc': 'Multitasking',
      'card-2-detail': `Aldin hat uns in den Bereichen Beratung, Ideen und Fotografie unterstützt. Auch die Zusammenarbeit mit unserem jetzigen Transporter verdanken wir ihm. Aldin ist sehr multitaskingfähig und ein sehr zuverlässiger Partner.`,
      'card-3-title': 'Besnik',
      'card-3-desc': 'Transporter',
      'card-3-detail': `Besnik Tafallari ist nicht nur unser offizieller GalaxyBalls-Transporter, sondern auch das beste Jason Statham-Double der Welt. Wir fanden ihn so interessant, dass eine Zusammenarbeit unausweichlich war.`,
      'card-4-title': 'Samafro',
      'card-4-desc': 'Videomacher',
      'card-4-detail': `Samafaro hat uns einige sehr schöne Videoaufnahmen aus der ganzen Welt gemacht. Seine Aufnahmen sind von höchster Qualität, ebenso wie seine Arbeit.`,
      'card-5-title': 'John',
      'card-5-desc': 'Designer',
      'card-5-detail': `John ist ein Meister des Designs, wir verdanken ihm die Website, die App und vieles mehr. Seine Arbeit ist großartig und es war ein Vergnügen, mit ihm zu arbeiten und viele schlaflose Nächte zu haben.`,
      'card-6-title': 'Alicia',
      'card-6-desc': 'Software Beratung',
      'card-6-detail': `Alicia ist eine Entwicklerin in Deutschland. Sie war für die Beratung des Projekts verantwortlich und war eine große Unterstützung für uns.`,
      'card-7-title': 'Crowdfunding',
      'card-7-desc': 'Liste aller Superhelden',
      'card-7-detail': `Hier wirst du bald alle Superhelden finden, die uns auf ulule.com und Kickstarter unterstützt haben. Mach mit!`,
      'card-8-title': 'Möchten Sie sich uns anschließen?',
      'card-8-desc': 'Kontaktieren Sie uns!',
      'card-8-detail': `Wir sind immer bereit, mit anderen Talenten zusammenzuarbeiten. Egal, ob du ein Designer, Künstler, Influencer, etc. bist, melde dich einfach bei uns, damit wir dich in das Galaxyballs-Projekt einbinden können!`,
      officialsite: 'Offizielle Website',
    },
    'space-balls': {
      // intro section
      title: 'SpaceBalls',
      desc: 'Die SpaceBalls sind hier und warten auf dich. Erleben Sie in Augment Realty einzigartige Momente, die Sie noch nie gesehen haben!',

      // chance section
      'chance-to-win': 'Ihre Chance zu gewinnen!',
      steps: 'Schritte',
      'find-balls': 'Finden',
      scan: 'Scannen',
      win: 'Gewinnen',

      // feature-section
      'about-space-balls': 'Mehr über SpaceBalls',
      'about-text': 'Drei Dinge, die Sie über die SpaceBalls wissen sollten',
      'about-desc-1': 'Dein Level steigt und du wirst in eine Rangliste eingetragen',
      'about-desc-2': 'Sie sind über die ganze Welt verstreut',
      'about-desc-3': 'Es gibt sie in verschiedenen Farben, Größen und einige sind selten',
      'find-a-ball': 'Was passiert, wenn du einen SpaceBall findest?',
      'find-a-ball-text': 'Drei weitere wichtige Dinge, die du wissen solltest',
      'find-desc-4': 'Du erhälst jedes Mal Erfahrungspunkte',
      'find-desc-5': 'Alle SpaceBalls landen in deiner Tasche und viele haben verschiedene Funktionen, die dir helfen, im Spiel voranzukommen.',
      'find-desc-6': 'Du bekommst 3 verschiedene Dinge, die dich weiterbringen werden',

      // adventure-section
      'what-else': 'Was noch',
      'adventure-coming-soon': 'Das größte Abenteuer kommt bald...',
      'adventure-text': ` Zwei Spiele sind in der App verfügbar und sorgen für noch mehr Spaß und Abenteuer. <br />
      <br />
      Der zweite Teil des Spiels ist besonders für Gamer und Entdecker interessant. Jeden Tag warten neue Abenteuer, Herausforderungen und sehr wertvolle SpaceBalls auf dich.
      <br />
      <br />
      Mit einigen dieser SpaceBalls kannst du weitere Spieloptionen freischalten, um dein Level zu erhöhen, Ranglisteneinträge zu erhalten und Preise zu gewinnen. Außerdem gibt es einen Shop, der dir helfen wird, deine Ziele schneller zu erreichen.`,

      // values-section
      rankinglist: 'Rangliste',
      'rankinglist-desc': 'Tragen Sie sich in die Rangliste ein, damit jeder Sie sehen kann.',
      chat: 'Chatten',
      'chat-desc': 'Chatten Sie mit Ihrem Team und mit anderen Benutzern weltweit',
      team: 'Team',
      'team-desc':
        'Bilde ein Team für die Suche nach den SpaceBalls und GalaxyBalls. Das erhöht deine Chance, alle Bälle noch schneller und effizienter zu finden.',
      winners: 'Gewinner',
      'winners-desc': 'Gewinne tolle Preise. Je mehr Kugel du findest, desto größer werden deine Geschenke sein.',

      // final-section
      finally: 'FinallyZum Schluss',
      'search-and-enjoy': 'Suchen und genießen!',
      'search-and-enjoy-desc':
        'Entdecke viele Schätze die in jedem SpaceBall versteckt sind. Es warten tolle Überraschungen auf dich, die du noch nie gesehen hast. Geh allein oder mit deinen Freunden auf die Jagd nach vielen galaktischen Bällen und fülle deine Schatztruhe. Schau täglich in die App, um keine Gelegenheit zu verpassen.',
      'you-can-also': 'Du kannst auch...',
      'extend-bag': 'Deine Tasche erweitern um mehr SpaceBalls zu sammeln',
      'get-your-detector': 'Einen Detektor kaufen um die passenden SpaceBalls zu finden.',
      'participate-events': 'An speziellen Events teilnehmen, um limitierte SpaceBalls zu finden.',

      // more-section
      'more-about': 'Mehr über unsere SpaceBalls',
      'more-about-text': 'Sieh dir die verschiedenen SpaceBalls an und merke dir, welche die wertvollsten sind',
    },
    footer: {
      'footer-text': 'bald verfügbar',
    },
  },

  pt: {
    menu: {
      home: 'Home',
      start: 'Início',
      rules: 'Regras',
      'world-map': 'World Map',
      winner: 'Vencedores',
      'space-balls': 'SpaceBalls',
      partner: 'Parceiros',
      transporter: 'Transportadores',
      faq: 'Faq',
    },
    home: {
      // game-section
      'for-players': 'Para jogadores',
      'winner-prize': 'Prêmio do vencedor',
      'winner-prize-text': 'Encontre todas as 7 GalaxyBalls em seu país e ganhe 10.000 €/$',
      'form-team': 'Forme uma equipe',
      'form-team-text':
        'As GalaxyBalls estão espalhadas por todo o país. Forme uma equipe e faça uma busca aventureira com amigos para aumentar suas chances de encontrar várias GalaxyBalls e ganhar o prêmio máximo de 10.000€/$',
      price: 'Prêmio por bola',
      'price-text': 'Para cada GalaxyBall que você encontra, você recebe 1.000 euros €/$',

      // rule-section
      rules: 'Regras',
      'rules-text': `No início do jogo, 7 GalaxyBalls são espalhadas no país e a localização aproximada é publicada aqui no site em "MAPA MUNDIAL" e no aplicativo GalaxyBalls em "MAPA MUNDIAL". No aplicativo GalaxyBalls em "RADAR", as bolas podem ser localizadas e encontradas nas proximidades imediatas. Uma vez que você tenha encontrado uma GalaxyBalls, você tem que escanear o código QR na bola para ser registrado como um encontrador oficial. Depois que todas as GalaxyBalls tiverem sido encontradas, você deve devolvê-las sem danos a uma de nossas unidades para receber seu prêmio em dinheiro.`,
      'rules-text-1': 'Se você encontrar uma GalaxyBall, receberá 1.000 €/$/crypto',
      'rules-text-2': 'Se você encontrar todas as 7 GalaxyBalls, receberá até 10.000 €/$/crypto',

      // world-map-section
      'world-map-title': 'Mapa mundial',
      'world-map-text': `Aqui você pode ver em qual país atualmente se encontram as GalaxyBalls. Você também pode descobrir em qual país no futuro as GalaxyBalls aterrissão.`,

      // winners-section
      'winners-title': 'Vencedores',
      'winners-text':
        'Aqui você pode encontrar todos os vencedores que acharam uma GalaxyBalls em seu país. Encontre as bolas e seja incluído no ranking. Quanto mais GalaxyBalls você encontrar, mais inscrições você terá!',
      'winners-text-1': 'Garantia de pagamento dos ganhos',
      'winners-text-2': 'Todas regras você encontra em nossos Termos e Condições Gerais',
      'winners-button': 'Lista inteira',

      // conditions-section
      'conditions-title': `Condições para o início`,
      'conditions-text': `Baixe o aplicativo GalaxyBalls e cadastre-se com seu endereço de e-mail. Então tudo o que você precisa fazer é encontrar 5 SpaceBalls (bolas virtuais) para ativar completamente seu GalaxyRadar e você está preparado para começar.`,

      // prize-section
      'prize-title': 'Seus prêmios estão esperando por você',
      'prize-text': `Muitas GalaxyBalls já estão se aproximando da Terra. Esteja entre os primeiros a ir em busca deles e receba um prêmio galáctico!`,

      // faq-section
      'faq-title': 'FAQ',
      'faq-description': 'Aqui você encontrará todas as perguntas importantes e freqüentes.',
      'question-description-1': 'Quem pode participar?',
      'answer-description-1': `Qualquer pessoa pode participar, não importa de onde seja. O único requisito é a instalação do aplicativo GalaxyBalls.`,
      'question-description-2': 'Onde posso encontrar as balas?',
      'answer-description-2': `No início do jogo, sete bolas são distribuídas para o país selecionado. Os locais aproximados podem ser encontrados no Mapa Mundial no site e no aplicativo GalaxyBalls. Ligue o radar e os encontre.`,
      'question-description-3': 'O que eu faço quando encontro uma bola?',
      'answer-description-3': `Quando você encontra uma bola, você tem que escanear o código QR nela. No seu menú você encontrará o ícone do scanner, clique nele. Uma vez que você fez isso, será registrado em nosso servidor como um achador oficial e a bola será desativada.`,
      'question-description-4': 'Quanto é que posso ganhar?',
      'answer-description-4':
        'Se você encontrar uma bola sozinho ou em uma equipe, você ganha 1000 €/$ ou em crypto em moeda nacional. Se você encontrar todas as 7 bolas, o prêmio principal é de 10.000 €/$ ou crypto.',
      'question-description-5': 'Quem esconde as bolas?',
      'answer-description-5':
        'Esta tarefa foi entregue ao Transportador Oficial Galaxy. Ele leva as bolas para 7 locais diferentes que são expelidos por um gerador randomizado.',
      'question-description-6': 'Como é que recebo o meu prémio monetário?',
      'answer-description-6':
        'Os achadores das GalaxyBalls têm que levar as bolas encontradas sem danos a um determinado lugar no respectivo país para receber seu prêmio em dinheiro.',
    },
    transporter: {
      'page-title': 'TRANSPORTADOR',
      desc: `Uma tarefa difícil somente pode ser realizada por alguém que tenha bastante experiência.`,
      'insta-link': `Transportador Galaxy`,
      title: `Nosso Transportador oficial das GalaxyBalls.`,
      details: `Ele é um mestre do transporte. 
      <br />
      <br />
      Seu trabalho é transportar as GalaxyBalls de um país para outro, algo que ele já fez dezenas de vezes, e ele sabe exatamente o que faz. Ele se assegura de que os jogos funcionem com segurança e que as regras sejam seguidas.
      <br />
      <br />
      Por esta razão, contratamos um Transportador como nosso agente para a distribuição das GalaxyBalls. Só ele garantirá que as GalaxyBalls cheguem até você. Quando você encontrar uma delas, você também encontrará o transportador.`,
    },
    partners: {
      title: 'Parceiros',
      desc: `Aqui você encontra alguns dos parceiros que trabalharam no projeto GalaxyBalls e nos apoiaram com seu conhecimento. Cada um deles contribuiu com algo que tornou este projeto único e é assim que chegamos a este resultado.`,
      'card-1-title': 'Blend',
      'card-1-desc': 'Conselheiro',
      'card-1-detail': `Blend nos ajudou nas áreas de conselhos e idéias. Ele foi um dos primeiros parceiros neste projeto e possibilitou outros contatos como com o Aldin e depois também com o Transportador.`,
      'card-2-title': 'Aldin',
      'card-2-desc': 'Multitarefa',
      'card-2-detail': `Aldin tem nos apoiado nas áreas de conselhos, idéias e fotografia. Também devemos a ele a cooperação com nosso atual transportador. O Aldin é muito multifunção e um parceiro muito confiável.`,
      'card-3-title': 'Besnik',
      'card-3-desc': 'Transportador',
      'card-3-detail': `Besnik Tafallari não é apenas nosso transportador oficial das GalaxyBalls, mas também o melhor dublê de Jason Statham do mundo. Achamos ele tão interessante que uma cooperação era inevitável.`,
      'card-4-title': 'Samafro',
      'card-4-desc': 'Criador de vídeo',
      'card-4-detail': `Samafaro produziu algumas filmagens de vídeo muito belas de todo o mundo. Suas filmagens são da mais alta qualidade, assim como seu trabalho.`,
      'card-5-title': 'John',
      'card-5-desc': 'Designer',
      'card-5-detail': `John é um mestre do design, devemos a ele o site, o aplicativo e muito mais. Seu trabalho é ótimo e foi um prazer trabalhar com ele e passar por muitas noites sem dormir.`,
      'card-6-title': 'Alicia',
      'card-6-desc': 'Consultoria de software',
      'card-6-detail': `Alicia é uma desenvolvedora na Alemanha. Ela foi responsável por aconselhar o projeto e foi um grande apoio para nós.`,
      'card-7-title': 'Crowdfunding',
      'card-7-desc': 'Lista de todos os super-heróis',
      'card-7-detail': `Em breve você encontrará aqui todos os super-heróis que nos apoiaram no ulule.com e no Kickstarter. Junte-se a nós!`,
      'card-8-title': 'Gostaria de se juntar a nós?',
      'card-8-desc': 'Entre em contato conosco!',
      'card-8-detail': `Estamos sempre dispostos a trabalhar em conjunto com outros talentos. Se você é designer, artista, influenciador, etc., basta entrar em contato para que possamos envolver você no projeto Galaxyballs!`,
      officialsite: 'Site oficial',
    },
    'space-balls': {
      // intro section
      title: 'SpaceBalls',
      desc: 'As SpaceBalls chegaram e estão esperando por você. Experimente momentos únicos em Argumented Realty nunca antes vistos!',

      // chance section
      'chance-to-win': 'Sua chance de vencer!',
      steps: 'Passos',
      'find-balls': 'Encontrar',
      scan: 'Escanear',
      win: 'Ganhar',

      // feature-section
      'about-space-balls': 'Mais sobre SpaceBalls',
      'about-text': 'Três coisas que você deve saber sobre as SpaceBalls',
      'about-desc-1': 'Seu nível sobe e você é incluído em uma lista de classificação',
      'about-desc-2': 'Estão espalhados pelo mundo inteiro',
      'about-desc-3': 'Existem em diferentes cores, tamanhos e alguns são raros.',
      'find-a-ball': 'O que acontece quando você encontra uma SpaceBall?',
      'find-a-ball-text': 'Três outras coisas importantes que você deve saber',
      'find-desc-4': 'Todas as vezes você ganha pontos de experiência',
      'find-desc-5': 'As SpaceBalls acabam ficando em seu bolso e muitas têm funções diferentes que te ajudam a progredir no jogo.',
      'find-desc-6': 'Você recebe 3 coisas diferentes que o ajudarão no seu progresso',

      // adventure-section
      'what-else': 'O que mais',
      'adventure-coming-soon': 'A maior aventura está por vir...',
      'adventure-text': `Dois jogos estão disponíveis no aplicativo e oferecem ainda mais diversão e aventura. <br />
      <br />
      A segunda parte do jogo é particularmente interessante para os gamers e exploradores. Todos os dias, novas aventuras, desafios e SpaceBalls muito valiosas esperam por você.
      <br />
      <br />
      Com algumas dessas bolas espaciais você pode desbloquear mais opções de jogo para subir de nível, entrar no ranking e ganhar prêmios. Há também uma loja que o ajudará a atingir seus objetivos com mais rapidez.`,

      // values-section
      rankinglist: 'Lista de ranking ',
      'rankinglist-desc': 'Inscreva-se na lista de classificação para que todos possam vê-lo.',
      chat: 'Bate-papo',
      'chat-desc': 'Converse com sua equipe e com outros usuários em todo o mundo',
      team: 'Equipe',
      'team-desc':
        'Forme uma equipe para procurar as SpaceBalls e GalaxyBalls. Isto aumenta suas chances de encontrar todas as bolas ainda mais rápido e mais eficáz.',
      winners: 'Vencedores',
      'winners-desc': 'Ganhe ótimos prêmios. Quanto mais bolas você encontrar, maiores serão seus presentes.',

      // final-section
      finally: 'Em conclusão',
      'search-and-enjoy': 'Procurar e aproveitar!',
      'search-and-enjoy-desc':
        'Descubra muitos tesouros que estão escondidos em cada SpaceBall. Há grandes surpresas esperando por você, que você nunca viu antes. Saia para caçar as muitas bolas galácticas sozinho ou com seus amigos e encha seu baú de tesouros. Confira o aplicativo diariamente para ter certeza de nunca perder uma oportunidade.',
      'you-can-also': 'Você também pode...',
      'extend-bag': 'Ampliar sua bolsa para coletar mais SpaceBalls',
      'get-your-detector': 'Comprar um detector para encontrar as SpaceBalls adequadas.',
      'participate-events': 'Participar de eventos especiais a fim de encontrar as SpaceBalls de edição limitada.',

      // more-section
      'more-about': 'Mais sobre as nossas SpaceBalls',
      'more-about-text': 'Observe as diferentes SpaceBalls e repare quais são as mais valiosas',
    },
    footer: {
      'footer-text': 'disponível em breve',
    },
  },

  it: {
    menu: {
      home: 'Home',
      start: 'Inizio',
      rules: 'Regole',
      'world-map': 'World Map',
      winner: 'Vincitori',
      'space-balls': 'SpaceBalls',
      partner: 'Partner',
      transporter: 'Trasportatori',
      faq: 'Faq',
    },
    home: {
      // game-section
      'for-players': 'Per i giocatori',
      'winner-prize': 'Premio per il vincitore',
      'winner-prize-text': 'Trova tutti i 7 GalaxyBalls nel tuo paese e vinci 10.000 € /$',
      'form-team': 'Formare una squadra',
      'form-team-text': `I GalaxyBall sono sparsi in tutto il Paese. Formate una squadra e partite per un'avventurosa ricerca con gli amici per aumentare le possibilità di trovare più GalaxyBall e vincere il primo premio di 10.000 € /$`,
      price: 'Prezzo per ogni pallone',
      'price-text': 'Per ogni GalaxyBall trovata riceverai 1.000 € /$',

      // rule-section
      rules: 'Regole',
      'rules-text': `All'inizio del gioco, 7 GalaxyBalls sono distribuite in un paese e la posizione approssimativa è pubblicata qui sul sito web alla sotto "MAPPA DEL MONDO" e nell'app GalaxyBalls alla sotto "MAPPA DEL MONDO". Con l'app GalaxyBalls alla sotto "RADAR", le palline possono essere localizzate e trovate nelle immediate vicinanze. Una volta trovata una GalaxyBall, il codice QR sulla palla deve essere scansionato per essere registrato come cercatore ufficiale. Dopo aver trovato tutte le GalaxyBall, è necessario restituirle integre a una delle nostre sedi per ricevere il premio.`,
      'rules-text-1': 'Se trovate una GalaxyBalls, riceverete 1.000 €/$/ cripto.',
      'rules-text-2': 'Se trovate tutte e 7 le GalaxyBalls, riceverete anche 10.000 €/$/ cripto.',

      // world-map-section
      'world-map-title': 'World Map',
      'world-map-text': `Qui è possibile vedere in quale paese si trovano attualmente le GalaxyBalls. È anche possibile scoprire in quale paese futuro atterreranno le GalaxyBalls. `,

      // winners-section
      'winners-title': 'Vincitore',
      'winners-text':
        'Qui potete trovare tutti i vincitori che hanno trovato un GalaxyBalls nel vostro paese. Trova le GalaxyBalls ed entra nella classifica. Più GalaxyBall si trovano, più ingressi si ottengono!',
      'winners-text-1': 'Pagamento garantito delle vincite',
      'winners-text-2': 'Troverete tutte le regole nei nostri Termini e Condizioni Generali.',
      'winners-button': 'Elenco completo',

      // conditions-section
      'conditions-title': `La condizione per l'avvio`,
      'conditions-text': `Scaricate l'app GalaxyBalls e registratevi con il vostro indirizzo e-mail. A questo punto basta trovare 5 SpaceBalls (sfere virtuali) per attivare completamente il GalaxyRadar e si è pronti a partire.`,

      // prize-section
      'prize-title': 'I vostri premi vi aspettano',
      'prize-text': `Molte sfere galattiche si stanno già avvicinando alla Terra. Siate tra i primi ad andare alla loro ricerca e riceverete una ricompensa galattica!`,

      // faq-section
      'faq-title': 'FAQ',
      'faq-description': 'Qui troverete tutte le domande più importanti e frequenti.',
      'question-description-1': 'Chi può partecipare?',
      'answer-description-1': `Chiunque può partecipare, indipendentemente dalla sua provenienza. L'unico requisito è installare l'applicazione GalaxyBalls.`,
      'question-description-2': 'Dove posso trovare le sfera?',
      'answer-description-2': `All'inizio della partita, vengono distribuite sette sfera al Paese selezionato. Le posizioni approssimative si trovano alla sotto Mappa del mondo sul sito web e nell'app GalaxyBalls. Accendete il radar e trovateli.`,
      'question-description-3': 'Cosa devo fare quando trovo un GalaxyBalls?',
      'answer-description-3': `Quando si trova una sfera, bisogna scansionare il codice QR su di essa. Nel menu si trova l'icona dello scanner, fare clic su di essa. Una volta fatto questo, sarete registrati nel nostro server come cercatore ufficiale e la sfera sarà disattivata.`,
      'question-description-4': 'Quanto posso vincere?',
      'answer-description-4':
        'Se trovate una sfera da soli o in squadra, vincete €/$1000 o criptovalute in valuta nazionale. Se si trovano tutte e 7 le sfere, il jackpot è di 10.000 €/$ o cripto.',
      'question-description-5': 'Chi nasconde le GalaxyBalls?',
      'answer-description-5':
        'Questo compito è stato affidato al nostro trasportatore ufficiale. Porta le GalaxyBall in 7 luoghi diversi. La loro posizione è generata in modo casuale da un sistema.',
      'question-description-6': 'Come si riceve il premio?',
      'answer-description-6':
        'Chi trova le GalaxyBalls deve portarle integre in un determinato luogo del paese in cui si trova per ricevere il premio.',
    },
    transporter: {
      'page-title': 'TRASPORTATORE',
      desc: `Un compito difficile può essere svolto solo da chi ha sufficiente esperienza.`,
      'insta-link': `Galaxy Transporter`,
      title: `Il nostro trasportatore ufficiale delle GalaxyBalls`,
      details: `È un maestro del trasporto.
      <br />
      <br />
      Il suo compito è trasportare le GalaxyBall da un Paese all'altro, cosa che ha fatto decine di volte, e sa esattamente cosa sta facendo. Si assicura che i giochi si svolgano in modo sicuro e che le regole vengano rispettate.
      <br />
      <br />
      Per questo motivo, abbiamo assunto un trasportatore come nostro agente per la distribuzione delle GalaxyBall. Solo lui farà in modo che le GalaxyBall arrivino a voi. Quando troverete uno di loro, incontrerete anche il trasportatore.`,
    },
    partners: {
      title: 'Partners',
      desc: `Qui troverete alcuni dei partner che hanno lavorato al progetto GalaxyBalls e che ci hanno messo a disposizione la loro esperienza. Ognuno di loro ha dato un contributo che ha reso questo progetto unico ed è così che siamo arrivati a questo risultato.`,
      'card-1-title': 'Blend',
      'card-1-desc': 'Consultazione',
      'card-1-detail': `Blend ci ha aiutato con consigli e idee. È stato uno dei primi partner di questo progetto e ha portato a ulteriori contatti come con aldin e poi anche con Transporter.`,
      'card-2-title': 'Aldin',
      'card-2-desc': 'Multitasking',
      'card-2-detail': `Aldin ci ha sostenuto con consigli, idee e fotografie. A lui dobbiamo anche la collaborazione con il nostro attuale furgone. Aldin è molto polivalente e un partner molto affidabile.`,
      'card-3-title': 'Besnik',
      'card-3-desc': 'Trasportatore',
      'card-3-detail': `Besnik Tafallari non è solo il nostro trasportatore ufficiale di GalaxyBalls, ma anche il miglior sosia di Jason Statham al mondo. Lo abbiamo trovato così interessante che la collaborazione è stata inevitabile.`,
      'card-4-title': 'Samafro',
      'card-4-desc': 'Creatore di video',
      'card-4-detail': `Samafaro ci ha realizzato dei bellissimi filmati da tutto il mondo. Le sue riprese sono di altissima qualità, così come il suo lavoro.`,
      'card-5-title': 'John',
      'card-5-desc': 'Consultazione',
      'card-5-detail': `John è un maestro del design, gli dobbiamo il sito web, l'app e molto altro. Il suo lavoro è ottimo ed è stato un piacere lavorare con lui e passare molte notti insonni.`,
      'card-6-title': 'Alicia',
      'card-6-desc': 'Consulenza software',
      'card-6-detail': `Alicia è una sviluppatrice in Germania. È stata responsabile della consulenza sul progetto e ci ha dato un grande supporto.`,
      'card-7-title': 'Crowdfunding',
      'card-7-desc': 'Elenco di tutti i supereroi',
      'card-7-detail': `Qui troverete presto tutti i supereroi che ci hanno sostenuto su ulule.com e Kickstarter. Partecipa anche tu!`,
      'card-8-title': 'Volete unirvi a noi?',
      'card-8-desc': 'Contattateci!',
      'card-8-detail': `Siamo sempre disposti a collaborare con altri talenti. Se sei un designer, un artista, un influencer, ecc. contattaci per farti coinvolgere nel progetto Galaxyballs!`,
      officialsite: 'Sito ufficiale',
    },
    'space-balls': {
      // intro section
      title: 'SpaceBalls',
      desc: 'Le SpaceBalls sono qui e ti aspettano. Vivete momenti unici che non avete mai visto prima in Augment Realty!',

      // chance section
      'chance-to-win': 'La possibilità di vincere!',
      steps: 'Passi',
      'find-balls': 'Trova',
      scan: 'Scansione',
      win: 'Vincere',

      // feature-section
      'about-space-balls': 'Ulteriori informazioni su SpaceBalls',
      'about-text': 'Tre cose da sapere sulle SpaceBalls',
      'find-a-ball': 'Cosa succede quando si trova una SpaceBall',
      'find-a-ball-text': 'Altre tre cose importanti da sapere',
      'about-desc-1': 'Il vostro livello aumenta e venite inseriti in una classifica',
      'about-desc-2': 'Sono sparsi in tutto il mondo',
      'about-desc-3': 'Sono disponibili in diversi colori e dimensioni e alcuni sono rari.',
      'find-desc-4': 'Si ottengono punti esperienza ogni volta',
      'find-desc-5': 'Tutte le SpaceBall finiscono in tasca e molte hanno diverse funzioni che aiutano a progredire nel gioco.',
      'find-desc-6': 'Ottenete 3 cose diverse che vi aiuteranno ad andare avanti',

      // adventure-section
      'what-else': `Cos'altro`,
      'adventure-coming-soon': 'La più grande avventura è in arrivo.... ',
      'adventure-text': `Nell'app sono disponibili due giochi che offrono ancora più divertimento e avventura.  <br />
      <br />
      La seconda parte del gioco è particolarmente interessante per i giocatori e gli esploratori. Ogni giorno ti aspettano nuove avventure, sfide e preziosissime SpaceBall.
      <br />
      <br />
      Con alcune di queste Balle spaziali, è possibile sbloccare altre opzioni di gioco per aumentare il livello, ottenere voci di classifica e vincere premi. C'è anche un negozio che vi aiuterà a raggiungere i vostri obiettivi più velocemente.`,

      // values-section
      rankinglist: 'Classifica ',
      'rankinglist-desc': 'Inseritevi nella classifica in modo che tutti possano vedervi.',
      chat: 'Chat',
      'chat-desc': 'Chatta con il tuo team e con altri utenti in tutto il mondo',
      team: 'Squadra ',
      'team-desc':
        'Formate una squadra per cercare le SpaceBall e le GalaxyBall. Questo aumenta le possibilità di trovare tutte le sfera in modo ancora più rapido ed efficiente.',
      winners: 'Vincitori ',
      'winners-desc': 'Vincere grandi premi. Più sfera troverete, più grandi saranno i vostri regali.',

      // final-section
      finally: 'In conclusione ',
      'search-and-enjoy': 'cercate e divertitevi!',
      'search-and-enjoy-desc': `Scopri tanti tesori nascosti in ogni SpaceBall. Vi aspettano grandi sorprese che non avete mai visto prima. Vai a caccia di tante sfere galattiche da solo o con i tuoi amici e riempi il tuo forziere. Controllate l'app ogni giorno per essere sicuri di non perdere mai un'opportunità.`,
      'you-can-also': 'Potete anche...',
      'extend-bag': 'Espandi la tua borsa per raccogliere altre SpaceBalls spaziali',
      'get-your-detector': 'Comprate un rilevatore per trovare le SpaceBalls spaziali corrispondenti.',
      'participate-events': 'Partecipate agli eventi speciali per trovare SpaceBalls in edizione limitata.',

      // more-section
      'more-about': 'Per saperne di più sulle nostre SpaceBalls',
      'more-about-text': 'Osservate le diverse SpaceBalls e notate quali sono le più preziose.',
    },
    footer: {
      'footer-text': 'presto disponibile',
    },
  },
}
